# Generated by Django 4.1.7 on 2023-04-15 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
